/*
  统一管理Action的类型
*/
export const TODOS_ADD = 'TODOS_ADD'
export const TODOS_DELETE = 'TODOS_DELETE'
export const TODOS_TOGGLE_ITEM = 'TODOS_TOGGLE_ITEM'
export const TODOS_TOGGLE_ALL = 'TODOS_TOGGLE_ALL'
export const TODOS_SHOW_EDIT_INPUT = 'TODOS_SHOW_EDIT_INPUT'
export const TODOS_EDIT_ETITLE = 'TODOS_EDIT_ETITLE'
export const TODOS_TOGGLE_TYPE = 'TODOS_TOGGLE_TYPE'
export const TODOS_CLEAR_ALL = 'TODOS_CLEAR_AL'
